<script type="text/javascript" src="<?=$this->baseUrl();?>/js/jquery/form/jquery.pstrength.js"></script>

<? if (isset($this->message)): ?>
<fieldset>
    <legend>INFORMATION SAVED</legend>
    <div class="box box-info closeable">
        <?= $this->message; ?>
    </div>
</fieldset>
<? endif; ?>

<form id="frmEditPassword" name="frmEditPassword" method="post" action="">
    <fieldset>
        <legend>CHANGE PASSWORD.</legend>
        <p>
            <label for="opasswd" class="required">Old password</label><br/>
            <input name="opasswd" id="opasswd" type="password" value="" maxlength="20" />
        </p>
        <p>
            <label for="newpasswd" class="required">New password</label><br/>
            <input name="newpasswd" id="newpasswd" type="password" class="password" value="" maxlength="20" />
        </p>
        <p>
            <label for="rpasswd" class="required">Retype password</label><br/>
            <input name="rpasswd" id="rpasswd" type="password" value="" maxlength="20" />
        </p>
    </fieldset>
    <p>
        <input class="btn btn-green big" value="Update Password" type="submit" />
    </p>

    <input type="hidden" name="kopel" id="kopel" value="<?=$this->row->kopel;?>">

    <div class="clear">&nbsp;</div>
</form>
<script type="text/javascript">
$('.password').pstrength();
$('#frmEditPassword').validate({
	rules: {
            opasswd: "required",
            newpasswd: "required",
            rpasswd: {
                required: true,
                equalTo: "#newpasswd"
            }
	},
	messages: {
		opasswd: "Enter old password",
		newpasswd: "Enter new password",
		rpasswd: {
                    required: "Please provide a password",
                    equalTo: "Please enter the same password as above"
		}
	}
});
</script>