<? $row = $this->row?>
<div class="span-33 append-2 prepend-2 prepend-top">
	<h2 class="alt">Congratulation your order has been recorded to our database.</h2>
	<hr>
<strong>
<br />
Your order has been recorded as order number : <font color="blue"><?=$row->orderId;?></font>.<br />
To continue the process,  please follow these stpes :
<ol>
	<li>Please Print this page. </li>
	<li>Please Go to the Bank and transfer fund as enlisted below. </li>
	<li>Please Please confirm your transfer with one of these method :
		<ul>
			<li>by email to layanan@hukumonline.com </li>
			<li>by web just click <a href="<?=KUTU_ROOT_URL?>/site/store_payment/confirm ">here</a></li>
			<li>by call to our customer service at (+62 21) 837 01837. </li>
			<li>by fax to (+62 21) 837 01826. </li>
		</ul>
	</li>
	<li>Please be patient and wait for your order.</li>
	<li>Your order will be in your place about 1-3 day(s) after confirmation.</li>
</ol>
<br />
</strong>
	<input type="button" class="btn" value="PRINT THIS PAGE" onclick="javascript:window.print();">
	<br>&nbsp;
	<fieldset>
	<legend>TO be PRINTED</legend>
	Order Id   : <?=$row->orderId; ?><br />
	Invoice    : <?=$row->invoiceNumber; ?> <br />
	Tax Number : <?=$row->taxNumber; ?> <br />
	Company : <?=$row->taxCompany; ?><br />
	Address : <?=$row->taxAddress; ?><br />
	City : <?=$row->taxCity; ?> <br />
	ZIP Code : <?=$row->taxZip; ?> <br />
	Province : <?=$row->taxProvince; ?>(<?=$row->taxCountryId; ?>)<br />
	Telp : <?=$row->telephone; ?> <br />
	Date : <?=$row->datePurchased; ?> <br />
	Total Fund Must be transfered : <strong><?=$row->orderTotal; ?></strong> <br />
	</fieldset>
 	<hr class ='white'>
</div>

